// 
// Decompiled by Procyon v0.6-prerelease
// 

package me.earth.earthhack.impl.managers.client;

import me.earth.earthhack.api.module.*;
import me.earth.earthhack.impl.*;
import me.earth.earthhack.impl.modules.client.autoconfig.*;
import me.earth.earthhack.impl.modules.client.clickgui.*;
import me.earth.earthhack.impl.modules.client.colors.*;
import me.earth.earthhack.impl.modules.client.commands.*;
import me.earth.earthhack.impl.modules.client.debug.*;
import me.earth.earthhack.impl.modules.client.customfont.*;
import me.earth.earthhack.impl.modules.client.hud.*;
import me.earth.earthhack.impl.modules.client.management.*;
import me.earth.earthhack.impl.modules.client.notifications.*;
import me.earth.earthhack.impl.modules.client.safety.*;
import me.earth.earthhack.impl.modules.client.server.*;
import me.earth.earthhack.impl.modules.client.tab.*;
import me.earth.earthhack.impl.modules.client.media.*;
import me.earth.earthhack.impl.modules.client.editor.*;
import me.earth.earthhack.impl.modules.combat.antisurround.*;
import me.earth.earthhack.impl.modules.combat.antitrap.*;
import me.earth.earthhack.impl.modules.combat.autothirtytwok.*;
import me.earth.earthhack.impl.modules.combat.anvilaura.*;
import me.earth.earthhack.impl.modules.combat.autoarmor.*;
import me.earth.earthhack.impl.modules.combat.autocrystal.*;
import me.earth.earthhack.impl.modules.combat.autotrap.*;
import me.earth.earthhack.impl.modules.combat.bedbomb.*;
import me.earth.earthhack.impl.modules.combat.bowspam.*;
import me.earth.earthhack.impl.modules.combat.criticals.*;
import me.earth.earthhack.impl.modules.combat.bomber.*;
import me.earth.earthhack.impl.modules.combat.bowkill.*;
import me.earth.earthhack.impl.modules.combat.holefiller.*;
import me.earth.earthhack.impl.modules.combat.killaura.*;
import me.earth.earthhack.impl.modules.combat.legswitch.*;
import me.earth.earthhack.impl.modules.combat.offhand.*;
import me.earth.earthhack.impl.modules.combat.pistonaura.*;
import me.earth.earthhack.impl.modules.combat.surround.*;
import me.earth.earthhack.impl.modules.combat.snowballer.*;
import me.earth.earthhack.impl.modules.combat.selftrap.*;
import me.earth.earthhack.impl.modules.combat.webaura.*;
import me.earth.earthhack.impl.modules.misc.announcer.*;
import me.earth.earthhack.impl.modules.misc.antiaim.*;
import me.earth.earthhack.impl.modules.misc.antipackets.*;
import me.earth.earthhack.impl.modules.misc.antipotion.*;
import me.earth.earthhack.impl.modules.misc.antivanish.*;
import me.earth.earthhack.impl.modules.misc.autoeat.*;
import me.earth.earthhack.impl.modules.misc.autofish.*;
import me.earth.earthhack.impl.modules.misc.autolog.*;
import me.earth.earthhack.impl.modules.misc.autoreconnect.*;
import me.earth.earthhack.impl.modules.misc.autorespawn.*;
import me.earth.earthhack.impl.modules.misc.buildheight.*;
import me.earth.earthhack.impl.modules.misc.chat.*;
import me.earth.earthhack.impl.modules.misc.extratab.*;
import me.earth.earthhack.impl.modules.misc.logger.*;
import me.earth.earthhack.impl.modules.misc.mcf.*;
import me.earth.earthhack.impl.modules.misc.mobowner.*;
import me.earth.earthhack.impl.modules.misc.noafk.*;
import me.earth.earthhack.impl.modules.misc.nohandshake.*;
import me.earth.earthhack.impl.modules.misc.nointeract.*;
import me.earth.earthhack.impl.modules.misc.nointerp.*;
import me.earth.earthhack.impl.modules.misc.nosoundlag.*;
import me.earth.earthhack.impl.modules.misc.nuker.*;
import me.earth.earthhack.impl.modules.misc.packets.*;
import me.earth.earthhack.impl.modules.misc.pingspoof.*;
import me.earth.earthhack.impl.modules.misc.portals.*;
import me.earth.earthhack.impl.modules.misc.settingspoof.*;
import me.earth.earthhack.impl.modules.misc.skinblink.*;
import me.earth.earthhack.impl.modules.misc.spammer.*;
import me.earth.earthhack.impl.modules.misc.tooltips.*;
import me.earth.earthhack.impl.modules.misc.tpssync.*;
import me.earth.earthhack.impl.modules.misc.tracker.*;
import me.earth.earthhack.impl.modules.misc.truedurability.*;
import me.earth.earthhack.impl.modules.misc.autocraft.*;
import me.earth.earthhack.impl.modules.misc.autoregear.*;
import me.earth.earthhack.impl.modules.misc.packetdelay.*;
import me.earth.earthhack.impl.modules.misc.rpc.*;
import me.earth.earthhack.impl.modules.movement.autosprint.*;
import me.earth.earthhack.impl.modules.movement.blocklag.*;
import me.earth.earthhack.impl.modules.movement.boatfly.*;
import me.earth.earthhack.impl.modules.movement.elytraflight.*;
import me.earth.earthhack.impl.modules.movement.entitycontrol.*;
import me.earth.earthhack.impl.modules.movement.entityspeed.*;
import me.earth.earthhack.impl.modules.movement.fastswim.*;
import me.earth.earthhack.impl.modules.movement.flight.*;
import me.earth.earthhack.impl.modules.movement.highjump.*;
import me.earth.earthhack.impl.modules.movement.holetp.*;
import me.earth.earthhack.impl.modules.movement.reversestep.*;
import me.earth.earthhack.impl.modules.movement.icespeed.*;
import me.earth.earthhack.impl.modules.movement.jesus.*;
import me.earth.earthhack.impl.modules.movement.longjump.*;
import me.earth.earthhack.impl.modules.movement.nofall.*;
import me.earth.earthhack.impl.modules.movement.antimove.*;
import me.earth.earthhack.impl.modules.movement.noslowdown.*;
import me.earth.earthhack.impl.modules.movement.packetfly.*;
import me.earth.earthhack.impl.modules.movement.phase.*;
import me.earth.earthhack.impl.modules.movement.safewalk.*;
import me.earth.earthhack.impl.modules.movement.speed.*;
import me.earth.earthhack.impl.modules.movement.step.*;
import me.earth.earthhack.impl.modules.movement.velocity.*;
import me.earth.earthhack.impl.modules.player.automine.*;
import me.earth.earthhack.impl.modules.player.autotool.*;
import me.earth.earthhack.impl.modules.player.blink.*;
import me.earth.earthhack.impl.modules.player.blocktweaks.*;
import me.earth.earthhack.impl.modules.player.cleaner.*;
import me.earth.earthhack.impl.modules.player.exptweaks.*;
import me.earth.earthhack.impl.modules.player.fakeplayer.*;
import me.earth.earthhack.impl.modules.player.fastplace.*;
import me.earth.earthhack.impl.modules.player.fasteat.*;
import me.earth.earthhack.impl.modules.player.freecam.*;
import me.earth.earthhack.impl.modules.player.liquids.*;
import me.earth.earthhack.impl.modules.player.mcp.*;
import me.earth.earthhack.impl.modules.player.multitask.*;
import me.earth.earthhack.impl.modules.player.ncptweaks.*;
import me.earth.earthhack.impl.modules.player.noglitchblocks.*;
import me.earth.earthhack.impl.modules.player.nohunger.*;
import me.earth.earthhack.impl.modules.player.norotate.*;
import me.earth.earthhack.impl.modules.player.arrows.*;
import me.earth.earthhack.impl.modules.player.raytrace.*;
import me.earth.earthhack.impl.modules.player.reach.*;
import me.earth.earthhack.impl.modules.player.replenish.*;
import me.earth.earthhack.impl.modules.player.scaffold.*;
import me.earth.earthhack.impl.modules.player.sorter.*;
import me.earth.earthhack.impl.modules.player.spectate.*;
import me.earth.earthhack.impl.modules.player.speedmine.*;
import me.earth.earthhack.impl.modules.player.suicide.*;
import me.earth.earthhack.impl.modules.player.timer.*;
import me.earth.earthhack.impl.modules.player.xcarry.*;
import me.earth.earthhack.impl.modules.render.blockhighlight.*;
import me.earth.earthhack.impl.modules.render.breadcrumbs.*;
import me.earth.earthhack.impl.modules.render.chams.*;
import me.earth.earthhack.impl.modules.render.esp.*;
import me.earth.earthhack.impl.modules.render.fullbright.*;
import me.earth.earthhack.impl.modules.render.holeesp.*;
import me.earth.earthhack.impl.modules.render.lagometer.*;
import me.earth.earthhack.impl.modules.render.logoutspots.*;
import me.earth.earthhack.impl.modules.render.voidesp.*;
import me.earth.earthhack.impl.modules.render.nametags.*;
import me.earth.earthhack.impl.modules.render.newchunks.*;
import me.earth.earthhack.impl.modules.render.norender.*;
import me.earth.earthhack.impl.modules.render.search.*;
import me.earth.earthhack.impl.modules.render.skeleton.*;
import me.earth.earthhack.impl.modules.render.sounds.*;
import me.earth.earthhack.impl.modules.render.tracers.*;
import me.earth.earthhack.impl.modules.render.viewclip.*;
import me.earth.earthhack.impl.modules.render.viewmodel.*;
import me.earth.earthhack.impl.modules.render.xray.*;
import me.earth.earthhack.impl.modules.render.crystalscale.*;
import me.earth.earthhack.impl.modules.render.trails.*;
import me.earth.earthhack.impl.modules.render.trajectories.*;
import me.earth.earthhack.impl.modules.render.penis.*;
import me.earth.earthhack.impl.modules.render.waypoints.*;
import me.earth.earthhack.impl.modules.render.weather.*;
import me.earth.earthhack.impl.modules.render.handchams.*;
import me.earth.earthhack.impl.modules.render.crystalchams.*;
import me.earth.earthhack.impl.modules.render.rainbowenchant.*;
import me.earth.earthhack.impl.modules.render.crosshair.*;
import me.earth.earthhack.impl.modules.render.popchams.*;
import me.earth.earthhack.impl.modules.client.pingbypass.*;
import me.earth.earthhack.api.event.bus.instance.*;
import me.earth.earthhack.impl.event.events.client.*;
import me.earth.earthhack.impl.modules.*;
import me.earth.earthhack.api.register.exception.*;
import me.earth.earthhack.api.register.*;
import me.earth.earthhack.api.module.util.*;
import java.util.*;
import me.earth.earthhack.api.util.interfaces.*;

public class ModuleManager extends IterationRegister<Module>
{
    public void init() {
        Earthhack.getLogger().info("Initializing Modules.");
        this.forceRegister(new AutoConfig());
        this.forceRegister(new ClickGui());
        this.forceRegister(new Colors());
        this.forceRegister(new Commands());
        this.forceRegister(new Debug());
        this.forceRegister(new FontMod());
        this.forceRegister(new HUD());
        this.forceRegister(new Management());
        this.forceRegister(new Notifications());
        this.forceRegister(new Safety());
        this.forceRegister(new ServerModule());
        this.forceRegister(new TabModule());
        this.forceRegister(new Media());
        this.forceRegister(new HudEditor());
        this.forceRegister(new AntiSurround());
        this.forceRegister(new AntiTrap());
        this.forceRegister(new Auto32k());
        this.forceRegister(new AnvilAura());
        this.forceRegister(new AutoArmor());
        this.forceRegister(new AutoCrystal());
        this.forceRegister(new AutoTrap());
        this.forceRegister(new BedBomb());
        this.forceRegister(new BowSpam());
        this.forceRegister(new Criticals());
        this.forceRegister(new CrystalBomber());
        this.forceRegister(new BowKiller());
        this.forceRegister(new HoleFiller());
        this.forceRegister(new KillAura());
        this.forceRegister(new LegSwitch());
        this.forceRegister(new Offhand());
        this.forceRegister(new PistonAura());
        this.forceRegister(new Surround());
        this.forceRegister(new Snowballer());
        this.forceRegister(new SelfTrap());
        this.forceRegister(new WebAura());
        this.forceRegister(new Announcer());
        this.forceRegister(new AntiAim());
        this.forceRegister(new AntiPackets());
        this.forceRegister(new AntiPotion());
        this.forceRegister(new AntiVanish());
        this.forceRegister(new AutoEat());
        this.forceRegister(new AutoFish());
        this.forceRegister(new AutoLog());
        this.forceRegister(new AutoReconnect());
        this.forceRegister(new AutoRespawn());
        this.forceRegister(new BuildHeight());
        this.forceRegister(new Chat());
        this.forceRegister(new ExtraTab());
        this.forceRegister(new Logger());
        this.forceRegister(new MCF());
        this.forceRegister(new MobOwner());
        this.forceRegister(new NoAFK());
        this.forceRegister(new NoHandShake());
        this.forceRegister(new NoInteract());
        this.forceRegister(new NoInterp());
        this.forceRegister(new NoSoundLag());
        this.forceRegister(new Nuker());
        this.forceRegister(new Packets());
        this.forceRegister(new PingSpoof());
        this.forceRegister(new Portals());
        this.forceRegister(new SettingSpoof());
        this.forceRegister(new SkinBlink());
        this.forceRegister(new Spammer());
        this.forceRegister(new ToolTips());
        this.forceRegister(new TpsSync());
        this.forceRegister(new Tracker());
        this.forceRegister(new TrueDurability());
        this.forceRegister(new AutoCraft());
        this.forceRegister(new AutoRegear());
        this.forceRegister(new PacketDelay());
        this.forceRegister(new RPC());
        this.forceRegister(new AutoSprint());
        this.forceRegister(new BlockLag());
        this.forceRegister(new BoatFly());
        this.forceRegister(new ElytraFlight());
        this.forceRegister(new EntityControl());
        this.forceRegister(new EntitySpeed());
        this.forceRegister(new FastSwim());
        this.forceRegister(new Flight());
        this.forceRegister(new HighJump());
        this.forceRegister(new HoleTP());
        this.forceRegister(new ReverseStep());
        this.forceRegister(new IceSpeed());
        this.forceRegister(new Jesus());
        this.forceRegister(new LongJump());
        this.forceRegister(new NoFall());
        this.forceRegister(new NoMove());
        this.forceRegister(new NoSlowDown());
        this.forceRegister(new PacketFly());
        this.forceRegister(new Phase());
        this.forceRegister(new SafeWalk());
        this.forceRegister(new Speed());
        this.forceRegister(new Step());
        this.forceRegister(new Velocity());
        this.forceRegister(new AutoMine());
        this.forceRegister(new AutoTool());
        this.forceRegister(new Blink());
        this.forceRegister(new BlockTweaks());
        this.forceRegister(new Cleaner());
        this.forceRegister(new ExpTweaks());
        this.forceRegister(new FakePlayer());
        this.forceRegister(new FastPlace());
        this.forceRegister(new FastEat());
        this.forceRegister(new Freecam());
        this.forceRegister(new LiquidInteract());
        this.forceRegister(new MiddleClickPearl());
        this.forceRegister(new MultiTask());
        this.forceRegister(new NCPTweaks());
        this.forceRegister(new NoGlitchBlocks());
        this.forceRegister(new NoHunger());
        this.forceRegister(new NoRotate());
        this.forceRegister(new Arrows());
        this.forceRegister(new RayTrace());
        this.forceRegister(new Reach());
        this.forceRegister(new Replenish());
        this.forceRegister(new Scaffold());
        this.forceRegister(new Sorter());
        this.forceRegister(new Spectate());
        this.forceRegister(new Speedmine());
        this.forceRegister(new Suicide());
        this.forceRegister(new Timer());
        this.forceRegister(new XCarry());
        this.forceRegister(new BlockHighlight());
        this.forceRegister(new BreadCrumbs());
        this.forceRegister(new Chams());
        this.forceRegister(new ESP());
        this.forceRegister(new Fullbright());
        this.forceRegister(new HoleESP());
        this.forceRegister(new LagOMeter());
        this.forceRegister(new LogoutSpots());
        this.forceRegister(new VoidESP());
        this.forceRegister(new Nametags());
        this.forceRegister(new NewChunks());
        this.forceRegister(new NoRender());
        this.forceRegister(new Search());
        this.forceRegister(new Skeleton());
        this.forceRegister(new Sounds());
        this.forceRegister(new Tracers());
        this.forceRegister(new CameraClip());
        this.forceRegister(new ViewModel());
        this.forceRegister(new XRay());
        this.forceRegister(new CrystalScale());
        this.forceRegister(new Trails());
        this.forceRegister(new Trajectories());
        this.forceRegister(new Penis());
        this.forceRegister(new WayPoints());
        this.forceRegister(new Weather());
        this.forceRegister(new HandChams());
        this.forceRegister(new CrystalChams());
        this.forceRegister(new RainbowEnchant());
        this.forceRegister(new Crosshair());
        this.forceRegister(new PopChams());
        this.forceRegister(new PingBypass());
        Bus.EVENT_BUS.post(new PostInitEvent());
    }
    
    public void load() {
        Caches.setManager(this);
        for (final Module module : this.getRegistered()) {
            module.load();
        }
    }
    
    @Override
    public void unregister(final Module module) throws CantUnregisterException {
        super.unregister(module);
        Bus.EVENT_BUS.unsubscribe(module);
    }
    
    private void forceRegister(final Module module) {
        this.registered.add((T)module);
        if (module instanceof Registrable) {
            ((Registrable)module).onRegister();
        }
    }
    
    public ArrayList<Module> getModulesFromCategory(final Category moduleCategory) {
        final ArrayList<Module> iModules = new ArrayList<Module>();
        for (final Module iModule : this.getRegistered()) {
            if (iModule.getCategory() == moduleCategory) {
                iModules.add(iModule);
            }
        }
        return iModules;
    }
}
